name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: check file
      run: ls -al
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_ID }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.HOST_PORT }}
        script_stop: true
        script: |
              ls -al
