name: SSHTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: writeSSHCommand
      run: ssh ${{ secrets.HOST_ID }}@${{ secrets.HOST_IP }} -p ${{ secrets.HOST_PORT }}
    - name: putPassword
      run: ${{ secrets.HOST_PASSWORD }}
    - name: TestCommand
      run: echo "test"
